{"timestamp":"2025-07-13T14:11:50.360187","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-13T14:11:50.363281","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/activefence.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-13T14:11:55.719521","level":"info","event":"Columns :                       article_id  ...              load_timestamp\n0                   cr5v2lz5vl6o  ...  2025-07-13T14:11:53.290589\n1                   c4g2ezl7xqyo  ...  2025-07-13T14:11:53.442252\n2  tech-now-chiles-lost-children  ...  2025-07-13T14:11:53.237801\n3                   c5ylkyrkjnzo  ...  2025-07-13T14:11:53.474412\n4                   cdxlqeyw95no  ...  2025-07-13T14:11:53.260307\n\n[5 rows x 5 columns]","logger":"unusual_prefix_0aab8e1abe4a8f324d874f9a30de87ad63865522_activefence"}
{"timestamp":"2025-07-13T14:11:55.785297Z","level":"error","event":"[2025-07-13T14:11:55Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-13T14:11:55.793637Z","level":"error","event":"[2025-07-13T14:11:55Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-13T14:11:55.796576Z","level":"error","event":"[2025-07-13T14:11:55Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-13T14:11:55.808347Z","level":"error","event":"[2025-07-13T14:11:55Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-13T14:11:55.811792Z","level":"error","event":"[2025-07-13T14:11:55Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-13T14:11:55.813607Z","level":"error","event":"[2025-07-13T14:11:55Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-13T14:11:56.943447","level":"error","event":"Bronze processing failed: The operation lacked the necessary privileges to complete for path bbc_tech/bronze/_delta_log/_last_checkpoint\n          \u001b[31m↳\u001b[0m Error performing GET https://s3.us-east-1.amazonaws.com/activefence-bucket/bbc_tech/bronze/_delta_log/_last_checkpoint in 1.124206485s - Server returned non-2xx status code\n           \u001b[31m↳\u001b[0m 403 Forbidden\n            \u001b[31m↳\u001b[0m <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>ZPnglo5gVhmWx1iC0FdY</AWSAccessKeyId><RequestId>KTQ082B18A944ZCN</RequestId><HostId>KcUzDboEHjCe/roTwAuTQ6A2jCguDM2luEpTUgOMVmuiKcz+NO240iATT7qIgc86+l+d3d2zlB4=</HostId></Error>\n","logger":"unusual_prefix_0aab8e1abe4a8f324d874f9a30de87ad63865522_activefence"}
{"timestamp":"2025-07-13T14:11:56.944703","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OSError","exc_value":"The operation lacked the necessary privileges to complete for path bbc_tech/bronze/_delta_log/_last_checkpoint\n          \u001b[31m↳\u001b[0m Error performing GET https://s3.us-east-1.amazonaws.com/activefence-bucket/bbc_tech/bronze/_delta_log/_last_checkpoint in 1.124206485s - Server returned non-2xx status code\n           \u001b[31m↳\u001b[0m 403 Forbidden\n            \u001b[31m↳\u001b[0m <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>ZPnglo5gVhmWx1iC0FdY</AWSAccessKeyId><RequestId>KTQ082B18A944ZCN</RequestId><HostId>KcUzDboEHjCe/roTwAuTQ6A2jCguDM2luEpTUgOMVmuiKcz+NO240iATT7qIgc86+l+d3d2zlB4=</HostId></Error>\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/activefence.py","lineno":142,"name":"process_bronze"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/deltalake/writer/writer.py","lineno":106,"name":"write_deltalake"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/deltalake/writer/_utils.py","lineno":32,"name":"try_get_table_and_table_uri"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/deltalake/writer/_utils.py","lineno":47,"name":"try_get_deltatable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/deltalake/table.py","lineno":161,"name":"__init__"}],"is_group":false,"exceptions":[]}]}
