{"timestamp":"2025-07-14T07:44:50.141758","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-14T07:44:50.142541","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/activefence.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-14T07:45:01.340623","level":"info","event":"Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.","logger":"chromadb.telemetry.product.posthog"}
{"timestamp":"2025-07-14T07:45:01.694748Z","level":"error","event":"[2025-07-14T07:45:01Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-14T07:45:01.700800Z","level":"error","event":"[2025-07-14T07:45:01Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-14T07:45:01.703378Z","level":"error","event":"[2025-07-14T07:45:01Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-14T07:45:01.721396Z","level":"error","event":"[2025-07-14T07:45:01Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-14T07:45:01.724092Z","level":"error","event":"[2025-07-14T07:45:01Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-14T07:45:01.726630Z","level":"error","event":"[2025-07-14T07:45:01Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-14T07:45:02.999296","level":"error","event":"Error processing Delta table: The operation lacked the necessary privileges to complete for path bbc_tech/silver/_delta_log/_last_checkpoint\n          \u001b[31m↳\u001b[0m Error performing GET https://s3.us-east-1.amazonaws.com/activefence-bucket/bbc_tech/silver/_delta_log/_last_checkpoint in 1.262614529s - Server returned non-2xx status code\n           \u001b[31m↳\u001b[0m 403 Forbidden\n            \u001b[31m↳\u001b[0m <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>ZPnglo5gVhmWx1iC0FdY</AWSAccessKeyId><RequestId>M9N0XGYP270G2GTW</RequestId><HostId>2VKbGLLlmlNuf6soHfuTFPrrj+6yH2Skv8VN/v4rjQFKijxKMukwwJVPH0cg0ntmJC8WpSrFXqo=</HostId></Error>\n","logger":"unusual_prefix_0aab8e1abe4a8f324d874f9a30de87ad63865522_activefence"}
{"timestamp":"2025-07-14T07:45:02.999602","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AttributeError","exc_value":"'Client' object has no attribute 'persist'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/activefence.py","lineno":317,"name":"embed_gold_data"}],"is_group":false,"exceptions":[]},{"exc_type":"OSError","exc_value":"The operation lacked the necessary privileges to complete for path bbc_tech/silver/_delta_log/_last_checkpoint\n          \u001b[31m↳\u001b[0m Error performing GET https://s3.us-east-1.amazonaws.com/activefence-bucket/bbc_tech/silver/_delta_log/_last_checkpoint in 1.262614529s - Server returned non-2xx status code\n           \u001b[31m↳\u001b[0m 403 Forbidden\n            \u001b[31m↳\u001b[0m <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>ZPnglo5gVhmWx1iC0FdY</AWSAccessKeyId><RequestId>M9N0XGYP270G2GTW</RequestId><HostId>2VKbGLLlmlNuf6soHfuTFPrrj+6yH2Skv8VN/v4rjQFKijxKMukwwJVPH0cg0ntmJC8WpSrFXqo=</HostId></Error>\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/airflow/dags/activefence.py","lineno":267,"name":"embed_gold_data"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/deltalake/table.py","lineno":161,"name":"__init__"}],"is_group":false,"exceptions":[]}]}
